name: workflow_Multiple_trigger_for_selected_branch
run-name: “workflow executed by @${{github.actor}}” # Defining how it will look like in github UI

on:
  push:
    branches:
      - prod
      - main

    paths:
      - 'src/**/*.txt'

  workflow_dispatch:
       
    
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print event_name"
        run: echo "This workflow was triggered by a ${{ github.event_name }} event" 
      - name: "Actor"
        run: echo "The triggering actor is ${{ github.triggering_actor }}"
      - name: "Pushed to branch"
        run:  |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          echo "File updated in '$BRANCH_NAME' branch " 
      - name: "Done"
        run: echo "Successfully completed..."
        
      
