name: callingWF
on: workflow_dispatch
jobs:
  call_with_all_values:
    name: "Calling sub workflow"
    uses: ./.github/workflows/callable_wf.yml
    with:
      ENV_NAME: prod
      LOOKUP_PATH: myPathName
      NON_MANDAT_VAL: "from calling workflow"
  
  call_with_only_mandory_values:
    name: "Calling sub workflow"
    uses: ./.github/workflows/callable_wf.yml
    with:
      ENV_NAME: prod
      LOOKUP_PATH: myPathName

  Finalize:
    needs: [call_with_all_values, call_with_only_mandory_values]
    runs-on: ubuntu-latest
    name: "EndJob"
    steps:
      - name: "End step"
        run: echo ""


        
      
