name: first-workflow
on: workflow_dispatch
jobs:
  expTrail:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Github context"
        run: echo "${{toJson(github)}}"
      - name: "Done"
        run: echo "Successfully completed..."
        
      
