name: "Job Artifacts and outputs Trail"
on: push
jobs: 
  build-job:
    runs-on: ubuntu-latest
    outputs:
      script-file-name: ${{steps.stepId.outputs.step-out-identifier}}   
    steps:
      - name: "GetCode"
        uses: actions/checkout@v4
        
      - name: "Install Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - name: "Install dependencies"
        # run: npm install
        run: npm ci  # is installs the dependencies with the versions locked/specified in the package-lock.json

      - name: "Build website"
        run: npm run build

      - name: "Publish file-name as output"
        id: stepId
        run: find dist/assests/*.js -type f -execdir echo 'step-out-identifier = {}' >>  $GITHUB_OUTPUT ';'
        # run: find dist/assests/*.js -type f -execdir echo 'step-out-identifier = Hello-world' >>  $GITHUB_OUTPUT ':'
				# run: find dist/assests/*.js -type f -execdir echo '::set-output  name= step-out-identifier:: {}' ';'


      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist-files # our choice
          path: dist           

  Deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: "Get artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: "list artifact contents"
        run: ls

      - name: “Print the output value from previous job”
        run: echo “${{needs.build-job.output.script-file-name }}”

  
# these jobs will run in parallel by default



        

      
          
      
